stages:
  - build
  - deploy


variables:
  FLUTTER_VERSION: "3.38.5"

before_script:
  - apt-get update -y
  - apt-get install -y curl git unzip xz-utils
  - curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
  - tar xf flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
  - export PATH="$PATH:$PWD/flutter/bin"
  - git config --global --add safe.directory $PWD/flutter
  - flutter doctor

build_web:
  stage: build
  script:
    - flutter pub get
    - flutter build web --release
  artifacts:
    paths:
      - build/web
  only:
    - master

deploy_to_vercel:
  stage: deploy
  image: node:18
  script:
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod --confirm --cwd build/web
  only:
    - master
